name: Create Docker image
description: Create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "./Dockerfile"
  image_name:
    description: "The name of the image"
    required: false
    default: "academy"
  tag_name:
    description: "The tag of the image"
    required: false
    default: ""
runs:
  using: composite
  steps:
    # Set image's properties in GITHUB_ENV (echo "TAG=$(date +%s)" >> $GITHUB_ENV)
    - name: Set image's properties in GITHUB_ENV
      run: |
            if [ -z "${{ inputs.tag_name }}" ]; then
              echo "TAG=latest" >> $GITHUB_ENV
            else
              echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
            fi
            echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}" >> $GITHUB_ENV
      shell: bash

    # Build an Application's image
    - name: Build Application's image
      run: docker build . --file ${{ inputs.dockerfile_path }} --tag $DOCKER_IMAGE_NAME:$TAG
      shell: bash

    # List Container images
    - name: List Container images
      run: docker images | grep "$DOCKER_IMAGE_NAME"
      shell: bash
