--liquibase formatted sql
--changeset Murilo Andrade (qxz0q3j):add-fk-constraint-to-tables
set search_path to workstation_rack;

ALTER TABLE T_TEAM_MEMBER
    ADD UNIQUE (CTW_CODE),
    ADD CONSTRAINT  FK_T_TEAM
        FOREIGN KEY (TEAM_ID) REFERENCES T_TEAM;

ALTER TABLE T_BOOKING
    ADD CONSTRAINT  FK_T_TEAM_MEMBER
        FOREIGN KEY (TEAM_MEMBER_ID) REFERENCES T_TEAM_MEMBER,
    ADD CONSTRAINT  FK_WORK_STATION_RACK
        FOREIGN KEY (WORK_STATION_RACK_ID) REFERENCES T_WORK_STATION_RACK;
