name: Create Docker image
description: Create a new Docker image
inputs:
  dockerhub_username:
    description: "Docker username"
    required: true
runs:
  using: composite
  steps:
    # Tag Docker image
    - name: Tag Docker image
      run: docker tag $DOCKER_IMAGE_NAME:$TAG ${{ inputs.dockerhub_username }}/github-actions-labs:$TAG
      shell: bash

    # Push to Docker Hub
    - name: Push to Docker Hub
      run: docker push ${{ inputs.dockerhub_username }}/github-actions-labs:$TAG
      shell: bash
